version: "1.0"
jobs:
  - name: "Install Dependencies"
    script: |
      echo "Starting installation..."
      npm i
      
  - name: "Run Linter"
    script: |
      echo "Running linter tests..."
      npm run dev
