version: "1.0"
jobs:
  - name: "Install Dependencies"
    script: |
      echo "Starting installation..."
      npm i
      
  - name: "copy file"
    script: |
      echo "Running linter tests..."
      cp -rf * D:\swg\g
      
  - name: "run"
    script: |
      echo "Running linter tests..."
      npm run start
  
