name: Deploy App
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy
        run: |
          curl -X POST \
            https://unushered-chantal-unpsychotic.ngrok-free.dev/api/v1/deployments/webhook/trigger \
            -H "Content-Type: application/json" \
            -d '{
              "project_id": "2dc13027-3997-41a5-9bf2-0863a3802568",
              "token": "${{ secrets.INFRA_CD_DEPLOY_TOKEN }}",
              "branch": "${{ github.ref_name }}",
              "commit_sha": "${{ github.sha }}"
            }'
